# https://github.com/btford/write-good
- id: write-good
  name: write-good
  description: Check docs for English prose with write-good
  entry: write-good
  args: []
  language: system
  types: [text]
  files: "\\.(rst|md|markdown|mdown|mkdn)$"

# https://github.com/igorshubovych/markdownlint-cli
- id: markdownlint
  name: markdownlint
  description: Checks the style of Markdown/Commonmark files.
  entry: markdownlint
  args: [--fix]
  language: system
  types: [text]
  files: "\\.(rst|md|markdown|mdown|mkdn)$"
  minimum_pre_commit_version: 0.15.0
