# https://github.com/btford/write-good
- id: write-good
  name: write-good
  description: Check docs for English prose with write-good
  entry: write-good
  args: []
  language: system
  types: [text]
  files: "\\.(rst|md|markdown|mdown|mkdn)$"

# https://github.com/igorshubovych/markdownlint-cli
- id: markdownlint
  name: markdownlint
  description: Checks the style of Markdown/Commonmark files.
  entry: markdownlint
  args: [--fix]
  language: system
  types: [text]
  files: "\\.(rst|md|markdown|mdown|mkdn)$"
  minimum_pre_commit_version: 0.15.0

# https://github.com/koalaman/shellcheck
- id: shellcheck
  name: shellcheck
  description: Static analysis tool for shell scripts
  entry: shellcheck
  args: []
  language: system
  files: "\\.(sh|bash)$"
  types: [text]

# https://github.com/mvdan/sh
- id: shfmt
  name: shfmt
  description: Shell formatter
  entry: shfmt
  args: [-l -w]
  language: system
  files: "\\.(sh|bash)$"
  types: [text]

# https://github.com/adrienverge/yamllint
- id: yamllint
  name: yamllint
  description: This hook runs yamllint.
  entry: yamllint
  args: []
  language: system
  files: "\\.(yaml|yml)$"
  types: [text]
