# https://github.com/btford/write-good
- id: write-good
  name: write-good
  description: Check docs for English prose with write-good
  entry: write-good
  args: []
  language: system
  types: [text]
  files: "\\.(rst|md|markdown|mdown|mkdn)$"
